import React, { useEffect, useMemo, useState } from 'react'
import { AlertCircle, ArrowRight, Brain, CheckCircle2, Clock3, Play, RotateCcw, Target, X } from 'lucide-react'
import Mascot from './Mascot'
import { AttemptRepository } from '../lib/attemptRepository'
import { getWeakSkills } from '../lib/skillMasteryService'
import { ReviewQueueService } from '../lib/reviewQueueService'
import { ERROR_TAGS } from '../lib/skillTaxonomy'
import { foundationLessonById } from '../data/foundationCurriculum'

export default function PracticePage({onOpenLesson}){
  const [tick,setTick]=useState(0);const [session,setSession]=useState(false)
  useEffect(()=>{const refresh=()=>setTick(v=>v+1);window.addEventListener('bunny-attempt-updated',refresh);window.addEventListener('bunny-review-updated',refresh);return()=>{window.removeEventListener('bunny-attempt-updated',refresh);window.removeEventListener('bunny-review-updated',refresh)}},[])
  const due=useMemo(()=>ReviewQueueService.due(),[tick]);const upcoming=useMemo(()=>ReviewQueueService.upcoming(12),[tick]);const weak=useMemo(()=>getWeakSkills(5),[tick]);const mistakes=useMemo(()=>AttemptRepository.recent(30).filter(a=>!a.correct).slice(0,6),[tick])
  return <div className="space-y-6"><section className="rounded-[30px] border border-slate-200 bg-white p-6 card-shadow sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-700">Practice</p><h1 className="mt-2 text-3xl font-black">Ôn đúng thứ bạn đang cần.</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-slate-500">Bunny ưu tiên lỗi gần đây, kỹ năng còn yếu và những nội dung đã đến lúc cần nhớ lại.</p></div><Mascot size={118} mood="encouraging"/></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[28px] border border-blue-100 bg-blue-50/60 p-5 card-shadow"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-700">Today's Review</p><h2 className="mt-1 text-2xl font-black">{due.length} mục cần ôn</h2><p className="mt-1 text-xs font-semibold text-slate-500">Khoảng {Math.max(1,Math.ceil(due.length*.65))} phút</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-blue-700"><Clock3 className="h-5 w-5"/></div></div>{due.length?<div className="mt-5 space-y-2">{due.slice(0,4).map(item=><div key={item.key} className="rounded-2xl border border-blue-100 bg-white p-3"><p className="text-sm font-black text-slate-900">{item.prompt}</p><p className="mt-1 text-[11px] font-bold text-slate-400">{(item.skillIds||[]).join(' · ')||'retrieval practice'}</p></div>)}</div>:<div className="mt-5 rounded-2xl bg-white p-4 text-sm font-semibold text-slate-500">Chưa có mục nào đến hạn. Hãy học hoặc thử một vài bài; review queue sẽ tự hình thành từ hoạt động thật.</div>}<button disabled={!due.length} onClick={()=>setSession(true)} className="pressable mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 px-4 text-sm font-black text-white disabled:opacity-40"><Play className="h-4 w-4"/> Bắt đầu ôn</button></div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><div className="flex items-center gap-3"><Target className="h-5 w-5 text-amber-600"/><div><p className="text-xs font-black uppercase tracking-[.14em] text-amber-700">Your Weak Areas</p><h2 className="mt-1 text-xl font-black">Kỹ năng cần thêm lượt luyện</h2></div></div><div className="mt-4 space-y-3">{weak.length?weak.map(skill=><div key={skill.skillId} className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black">{skill.labelVi}</p><p className="mt-1 text-[11px] font-semibold text-slate-400">{skill.attempts} lần thử · {skill.incorrect} lỗi</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${skill.masteryScore<50?'bg-red-50 text-red-700':skill.masteryScore<70?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{skill.masteryScore}%</span></div></div>):<EmptySmall text="Chưa đủ dữ liệu để xác định điểm yếu."/>}</div></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><div className="flex items-center gap-3"><Brain className="h-5 w-5 text-violet-600"/><h2 className="text-xl font-black">Quick Practice</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><QuickCard title="Sentence Builder" text="Mở rộng câu từng lớp" onClick={()=>onOpenLesson?.(foundationLessonById['f29-sentence-expansion'])}/><QuickCard title="Questions" text="Luyện be / do / does" onClick={()=>onOpenLesson?.(foundationLessonById['f27-questions'])}/></div></div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><div className="flex items-center gap-3"><AlertCircle className="h-5 w-5 text-red-600"/><h2 className="text-xl font-black">Recent Mistakes</h2></div><div className="mt-4 space-y-3">{mistakes.length?mistakes.map(a=><button key={a.id} onClick={()=>onOpenLesson?.(foundationLessonById[a.lessonId])} className="w-full rounded-2xl border border-slate-100 bg-slate-50 p-3 text-left hover:border-blue-200"><p className="text-xs font-black text-slate-900">{a.answer||'No answer'}</p><p className="mt-1 text-[11px] font-semibold text-emerald-700">→ {a.expected}</p><p className="mt-1 text-[10px] font-bold text-red-600">{(a.errorTags||[]).map(t=>ERROR_TAGS[t]||t).join(' · ')||'Cần ôn lại'}</p></button>):<EmptySmall text="Chưa có lỗi gần đây. Khi bạn trả lời sai, Bunny sẽ đưa lỗi vào đây để ôn lại."/>}</div></div></section>
    {session&&<ReviewSession items={due} onClose={()=>setSession(false)}/>}</div>
}
function QuickCard({title,text,onClick}){return <button onClick={onClick} className="pressable flex min-h-24 items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left"><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs font-semibold text-slate-500">{text}</p></div><ArrowRight className="h-4 w-4 text-blue-600"/></button>}
function EmptySmall({text}){return <div className="rounded-2xl bg-slate-50 p-4 text-xs font-semibold leading-5 text-slate-500">{text}</div>}
function ReviewSession({items,onClose}){const [index,setIndex]=useState(0);const [open,setOpen]=useState(false);const item=items[index];if(!item)return <div/>;const rate=r=>{ReviewQueueService.recordRating(item,r);if(index>=items.length-1)onClose();else{setIndex(i=>i+1);setOpen(false)}};return <div className="fixed inset-0 z-[95] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-[.14em] text-blue-700">Review {index+1}/{items.length}</p><button onClick={onClose} className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100" aria-label="Đóng review"><X className="h-5 w-5"/></button></div><h2 className="mt-4 text-2xl font-black">{item.prompt}</h2>{!open?<button onClick={()=>setOpen(true)} className="pressable mt-6 min-h-12 w-full rounded-2xl bg-blue-600 px-4 text-sm font-black text-white">Tôi đã nghĩ xong — xem đáp án</button>:<><div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Đáp án</p><p className="mt-2 text-sm font-bold text-emerald-900">{item.expected}</p></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>rate(0)} className="min-h-12 rounded-xl border border-red-100 bg-red-50 text-xs font-black text-red-700">Chưa nhớ</button><button onClick={()=>rate(.5)} className="min-h-12 rounded-xl border border-amber-100 bg-amber-50 text-xs font-black text-amber-800">Gần đúng</button><button onClick={()=>rate(1)} className="min-h-12 rounded-xl border border-emerald-100 bg-emerald-50 text-xs font-black text-emerald-700">Nhớ rồi</button></div></>}</div></div>}
