// Build-time speech generation.
//
// Runs Kokoro once, on CI, and writes one audio file per phrase the course
// speaks. The app then plays a small MP3 instead of downloading and booting a
// ~90MB model in the learner's browser, which is what used to make the first
// audio press wait.
//
// Not part of `npm run build` on purpose: it needs to fetch the model, and the
// output is committed, so a normal deploy stays fast and offline-safe.
//
//   node scripts/generate-speech.mjs [--force]
import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { speechManifestEntries } from './speechManifest.mjs'

const OUT_DIR = 'public/voice'
const MANIFEST_FILE = 'src/data/speechClips.js'
const TMP_WAV = join(OUT_DIR, '.tmp.wav')
const force = process.argv.includes('--force')

function requireFfmpeg(){
  try { execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' }) }
  catch { throw new Error('ffmpeg is required to encode MP3 clips. Install it, or run this on the CI runner.') }
}

function encodeMp3(wavPath, mp3Path){
  execFileSync('ffmpeg', [
    '-y', '-loglevel', 'error',
    '-i', wavPath,
    '-codec:a', 'libmp3lame', '-b:a', '64k', '-ac', '1',
    mp3Path,
  ])
}

const entries = speechManifestEntries()
console.log(`Speech manifest: ${entries.length} clips`)

mkdirSync(OUT_DIR, { recursive: true })
requireFfmpeg()

const { KokoroTTS } = await import('kokoro-js')
console.log('Loading Kokoro (fp32 — this is a build step, so use the best weights)…')
const tts = await KokoroTTS.from_pretrained('onnx-community/Kokoro-82M-v1.0-ONNX', { dtype: 'fp32', device: 'cpu' })

let made = 0, reused = 0
for(const [index, entry] of entries.entries()){
  const mp3Path = join(OUT_DIR, `${entry.id}.mp3`)
  if(!force && existsSync(mp3Path)){ reused++; continue }
  const audio = await tts.generate(entry.text, { voice: entry.voice, speed: entry.speed })
  await audio.save(TMP_WAV)
  encodeMp3(TMP_WAV, mp3Path)
  made++
  if(made % 25 === 0 || index === entries.length - 1) console.log(`  ${index + 1}/${entries.length} …`)
}
rmSync(TMP_WAV, { force: true })

// Drop clips no longer referenced, so renamed curriculum text cannot leave
// orphaned audio behind in the repo.
const keep = new Set(entries.map(entry => `${entry.id}.mp3`))
let pruned = 0
for(const file of readdirSync(OUT_DIR)){
  if(file.endsWith('.mp3') && !keep.has(file)){ rmSync(join(OUT_DIR, file)); pruned++ }
}

const clips = Object.fromEntries(entries.map(entry => [entry.key, entry.id]))
writeFileSync(MANIFEST_FILE,
  '// Generated by scripts/generate-speech.mjs — do not edit by hand.\n' +
  `export default ${JSON.stringify({ generatedBy: 'kokoro-82m-v1.0', clips })}\n`)

const bytes = readdirSync(OUT_DIR)
  .filter(file => file.endsWith('.mp3'))
  .reduce((total, file) => total + statSync(join(OUT_DIR, file)).size, 0)

console.log(`Generated ${made}, reused ${reused}, pruned ${pruned}.`)
console.log(`${keep.size} clips, ${(bytes / 1024 / 1024).toFixed(2)} MB total.`)
