import React, { useEffect, useMemo, useState } from 'react'
import { BookOpen, Brain, ChevronRight, CircleUserRound, Home, Menu, PenLine, Puzzle, RotateCcw, Sparkles, Target, X } from 'lucide-react'
import Mascot from './components/Mascot'
import FoundationMap from './components/FoundationMap'
import PracticePage from './components/PracticePage'
import WritingPage from './components/WritingPage'
import LessonEngine from './components/lesson/LessonEngine'
import { foundationLessons, validateFoundationCurriculum } from './data/foundationCurriculum'
import { getAllProgress, isLessonPassed, resetFoundationProgress } from './lib/learningProgress'
import { getWeakSkills } from './lib/skillMasteryService'
import { ReviewQueueService } from './lib/reviewQueueService'

const nav=[{id:'home',label:'Trang chủ',short:'Home',icon:Home},{id:'learn',label:'Học',short:'Học',icon:BookOpen},{id:'practice',label:'Luyện tập',short:'Luyện',icon:Puzzle},{id:'write',label:'Viết',short:'Viết',icon:PenLine},{id:'profile',label:'Hồ sơ',short:'Hồ sơ',icon:CircleUserRound}]

export default function App(){
  const [active,setActive]=useState('home');const [drawer,setDrawer]=useState(false);const [lesson,setLesson]=useState(null);const [progress,setProgress]=useState(()=>getAllProgress());const [dataTick,setDataTick]=useState(0)
  useEffect(()=>{const fn=()=>setProgress(getAllProgress());const tick=()=>setDataTick(v=>v+1);window.addEventListener('bunny-progress-updated',fn);window.addEventListener('bunny-attempt-updated',tick);window.addEventListener('bunny-review-updated',tick);return()=>{window.removeEventListener('bunny-progress-updated',fn);window.removeEventListener('bunny-attempt-updated',tick);window.removeEventListener('bunny-review-updated',tick)}},[])
  const errors=useMemo(()=>validateFoundationCurriculum(),[]);useEffect(()=>{if(errors.length)console.error('Curriculum validation errors',errors)},[errors])
  const completed=foundationLessons.filter(l=>isLessonPassed(progress[l.id])).length;const firstUnfinished=foundationLessons.find(l=>!isLessonPassed(progress[l.id]))||foundationLessons[foundationLessons.length-1]
  const openLesson=l=>l&&setLesson(l)
  return <div className="min-h-screen hero-glow text-slate-900"><Sidebar active={active} setActive={setActive} completed={completed}/><MobileHeader onMenu={()=>setDrawer(true)}/>{drawer&&<Drawer active={active} setActive={setActive} onClose={()=>setDrawer(false)}/>}<main className="mx-auto w-full max-w-[1540px] px-4 pb-28 pt-5 sm:px-6 lg:pl-[280px] lg:pr-8 lg:pt-8">
    {active==='home'&&<HomePage completed={completed} progress={progress} current={firstUnfinished} onContinue={()=>openLesson(firstUnfinished)} onLearn={()=>setActive('learn')} dataTick={dataTick}/>} {active==='learn'&&<FoundationMap onOpenLesson={openLesson}/>} {active==='practice'&&<PracticePage onOpenLesson={openLesson}/>} {active==='write'&&<WritingPage onOpenLesson={openLesson}/>} {active==='profile'&&<Profile completed={completed} dataTick={dataTick} onReset={()=>{if(confirm('Reset all Foundation progress, attempts, and review data?'))resetFoundationProgress()}}/>}
  </main><BottomNav active={active} setActive={setActive}/>{lesson&&<LessonEngine lesson={lesson} onClose={()=>setLesson(null)} onComplete={()=>{setLesson(null);setActive('learn')}}/>}</div>
}

function Logo(){return <div className="flex items-center gap-2.5"><div className="grid h-10 w-10 place-items-center rounded-2xl border border-orange-100 bg-white card-shadow"><Mascot size={38} withBook={false}/></div><div className="leading-none"><div className="text-lg font-black tracking-tight"><span className="text-[#ef4444]">Bunny</span> <span className="text-[#247df4]">English</span></div><div className="mt-1 text-[9px] font-black uppercase tracking-[.18em] text-slate-400">Learn with clarity</div></div></div>}
function Sidebar({active,setActive,completed}){const total=foundationLessons.length;return <aside className="fixed inset-y-0 left-0 z-40 hidden w-[248px] border-r border-slate-200/80 bg-white/90 p-5 backdrop-blur-xl lg:flex lg:flex-col"><Logo/><div className="mt-7 rounded-3xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex items-center gap-3"><Mascot size={54} mood="encouraging"/><div><p className="text-xs font-bold text-slate-500">Foundation</p><p className="text-xl font-black text-slate-900">{completed}/{total}</p></div></div><div className="mt-3 h-2 rounded-full bg-white"><div className="progress-motion h-full rounded-full bg-blue-600" style={{width:`${completed/total*100}%`}}/></div></div><nav className="mt-6 space-y-2" aria-label="Điều hướng chính">{nav.map(item=>{const I=item.icon,s=active===item.id;return <button key={item.id} onClick={()=>setActive(item.id)} className={`pressable flex min-h-12 w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold ${s?'bg-blue-50 text-blue-700':'text-slate-500 hover:bg-slate-50'}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${s?'bg-blue-600 text-white':'bg-slate-100'}`}><I className="h-4.5 w-4.5"/></span>{item.label}{s&&<ChevronRight className="ml-auto h-4 w-4"/>}</button>})}</nav><div className="mt-auto rounded-3xl bg-[#102958] p-4 text-white"><div className="flex items-center gap-3"><Brain className="h-5 w-5 text-blue-300"/><p className="text-sm font-black">Cách bạn học</p></div><p className="mt-2 text-xs leading-5 text-blue-100">Hiểu → Luyện → Tự viết → Nhận phản hồi → Ôn lại.</p></div></aside>}
function MobileHeader({onMenu}){return <header className="sticky top-0 z-30 flex items-center justify-between border-b border-slate-200/70 bg-[color:var(--surface-muted)]/90 px-4 py-3 backdrop-blur-xl lg:hidden"><button onClick={onMenu} aria-label="Mở menu" className="pressable grid h-11 w-11 place-items-center rounded-xl bg-white card-shadow"><Menu className="h-5 w-5"/></button><Logo/><div className="grid h-11 min-w-11 place-items-center rounded-xl bg-white px-2 card-shadow" aria-label="Learning streak"><span className="text-sm font-black text-amber-600">🔥</span></div></header>}
function Drawer({active,setActive,onClose}){return <div className="fixed inset-0 z-50 lg:hidden"><button onClick={onClose} aria-label="Đóng menu" className="absolute inset-0 bg-slate-900/30"/><div className="absolute left-0 top-0 h-full w-[86%] max-w-sm bg-white p-5 shadow-2xl"><div className="flex justify-between"><Logo/><button onClick={onClose} aria-label="Đóng menu" className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100"><X className="h-5 w-5"/></button></div><nav className="mt-7 space-y-2">{nav.map(item=>{const I=item.icon;return <button key={item.id} onClick={()=>{setActive(item.id);onClose()}} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl px-4 py-3 font-bold ${active===item.id?'bg-blue-50 text-blue-700':'text-slate-600'}`}><I className="h-5 w-5"/>{item.label}</button>})}</nav></div></div>}
function BottomNav({active,setActive}){return <nav className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-[22px] border border-slate-200/80 bg-white/95 p-1.5 shadow-xl backdrop-blur-xl lg:hidden" aria-label="Điều hướng dưới">{nav.map(item=>{const I=item.icon,s=active===item.id;return <button key={item.id} onClick={()=>setActive(item.id)} className={`pressable flex min-h-14 flex-col items-center justify-center gap-1 rounded-2xl px-1 py-2 text-[11px] font-bold ${s?'bg-blue-50 text-blue-700':'text-slate-500'}`}><I className="h-5 w-5"/><span>{item.short}</span></button>})}</nav>}

function HomePage({completed,progress,current,onContinue,onLearn,dataTick}){const total=foundationLessons.length,pct=Math.round(completed/total*100);const hour=new Date().getHours();const greeting=hour<12?'Good morning!':hour<18?'Good afternoon!':'Good evening!';const currentProgress=progress[current.id];const lessonPct=currentProgress?.status==='in_progress'?Math.round(((currentProgress.lastStep+1)/current.steps.length)*100):0;const weak=useMemo(()=>getWeakSkills(3),[dataTick]);const due=useMemo(()=>ReviewQueueService.due().length,[dataTick]);return <div className="space-y-6"><section className="overflow-hidden rounded-[32px] border border-orange-100 bg-white card-shadow"><div className="grid gap-5 p-5 md:grid-cols-[1.35fr_.65fr] md:p-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700"><Sparkles className="h-3.5 w-3.5"/> {greeting}</div><h1 className="mt-4 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl xl:text-5xl">Build English <span className="text-blue-600">one clear step</span> at a time.</h1><p className="mt-4 max-w-3xl text-sm font-medium leading-7 text-slate-500">Học tiếng Anh từng bước, hiểu rõ từ nền tảng. Bắt đầu với câu đơn giản, luyện cấu trúc và dần tiến tới viết đoạn văn và bài luận.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={onContinue} className="pressable min-h-12 rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-100">{completed?'Tiếp tục học':'Bắt đầu Foundation'}</button><button onClick={onLearn} className="pressable min-h-12 rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-black text-slate-700">Xem lộ trình</button></div></div><div className="relative grid min-h-52 place-items-center rounded-[28px] bg-gradient-to-br from-blue-50 via-white to-orange-50 soft-grid"><Mascot size={176} mood="encouraging" className="floaty"/><div className="absolute bottom-4 right-4 rounded-2xl bg-white px-3 py-2 text-xs font-black text-blue-700 card-shadow">Hiểu rõ rồi mới tiến tiếp.</div></div></div></section>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[28px] border border-blue-100 bg-white p-5 card-shadow"><p className="text-xs font-black uppercase tracking-[.14em] text-blue-700">Continue Learning</p><div className="mt-3 flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{current.titleEn}</h2><p className="mt-1 text-sm font-semibold text-slate-400">Lesson {current.order} · {current.titleVi}</p></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-700">{lessonPct}%</span></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="progress-motion h-full rounded-full bg-blue-600" style={{width:`${lessonPct}%`}}/></div><button onClick={onContinue} className="pressable mt-5 inline-flex min-h-11 items-center gap-2 rounded-2xl bg-blue-600 px-5 text-sm font-black text-white">Tiếp tục <ChevronRight className="h-4 w-4"/></button></div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><p className="text-xs font-black uppercase tracking-[.14em] text-amber-700">Today's Goal</p><div className="mt-4 grid grid-cols-2 gap-3"><Goal value="1" label="lesson"/><Goal value={String(Math.max(5,due))} label="review items"/></div><p className="mt-4 text-xs font-semibold text-slate-500">Không có energy system. Bạn có thể học tiếp khi muốn.</p></div></section>
    <section className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Foundation Progress</p><h2 className="mt-1 text-2xl font-black">{completed} / {total}</h2></div><span className="text-3xl font-black text-emerald-600">{pct}%</span></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="progress-motion h-full rounded-full bg-emerald-500" style={{width:`${pct}%`}}/></div><div className="mt-5 flex flex-wrap gap-2">{['Foundation','Sentence Builder','Everyday English','Intermediate','Writing','Academic English','College English'].map((x,i)=><span key={x} className={`rounded-full px-3 py-2 text-xs font-black ${i===0?'bg-blue-50 text-blue-700':'bg-slate-50 text-slate-400'}`}>{x}{i>0?' · later':''}</span>)}</div></div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><div className="flex items-center gap-2"><Target className="h-5 w-5 text-red-600"/><p className="text-xs font-black uppercase tracking-[.14em] text-red-700">Needs Review</p></div><div className="mt-4 space-y-3">{weak.length?weak.map(s=><div key={s.skillId} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><p className="text-sm font-black">{s.labelVi}</p><p className="mt-1 text-[11px] font-semibold text-slate-400">{s.incorrect} lỗi gần đây</p></div><span className="text-xs font-black text-amber-700">{s.masteryScore}%</span></div>):<div className="rounded-2xl bg-slate-50 p-4 text-xs font-semibold leading-5 text-slate-500">Hãy hoàn thành vài bài; Bunny sẽ dùng lỗi thật để tìm điểm cần ôn.</div>}</div></div></section></div>}
function Goal({value,label}){return <div className="rounded-2xl bg-slate-50 p-4 text-center"><p className="text-2xl font-black text-slate-900">{value}</p><p className="mt-1 text-[11px] font-bold text-slate-500">{label}</p></div>}
function Profile({completed,onReset,dataTick}){const total=foundationLessons.length;const weak=useMemo(()=>getWeakSkills(5),[dataTick]);return <div className="space-y-5"><div className="rounded-[30px] border border-slate-200 bg-white p-7 card-shadow"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-24 w-24 place-items-center rounded-[28px] bg-blue-50"><Mascot size={88} mood="proud"/></div><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-700">Foundation learner</p><h1 className="mt-1 text-3xl font-black">Your learning profile</h1><p className="mt-2 text-sm text-slate-500">{completed}/{total} bài đã hoàn thành hoặc test out.</p></div></div></div><div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><h2 className="text-xl font-black">Weakness profile</h2><p className="mt-2 text-xs font-semibold text-slate-500">Mastery dùng prior đơn giản để một câu trả lời không tạo cảm giác chính xác giả.</p><div className="mt-4 space-y-2">{weak.map(s=><div key={s.skillId} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="text-sm font-bold">{s.labelVi}</span><span className="text-xs font-black text-slate-600">{s.masteryScore}% · {s.attempts} attempts</span></div>)}</div></div><button onClick={onReset} className="pressable inline-flex min-h-11 items-center gap-2 rounded-2xl border border-red-200 bg-white px-4 py-3 text-sm font-black text-red-600"><RotateCcw className="h-4 w-4"/> Reset learning data</button></div>}
