import React, { useEffect, useMemo, useState } from 'react'
import { AlertCircle, BookOpen, Brain, ChevronRight, CircleUserRound, Home, Menu, PenLine, Puzzle, RotateCcw, Sparkles, Target, X } from 'lucide-react'
import Mascot from './components/Mascot'
import FoundationMap from './components/FoundationMap'
import LessonEngine from './components/lesson/LessonEngine'
import { foundationLessonById, foundationLessons, validateFoundationCurriculum } from './data/foundationCurriculum'
import { getAllProgress, getErrorProfile, getReviewQueue, resetFoundationProgress } from './lib/learningProgress'
import { errorCategoryLabel } from './lib/learningAnalytics'

const nav = [
  { id:'home', label:'Trang chủ', icon:Home },
  { id:'learn', label:'Học', icon:BookOpen },
  { id:'practice', label:'Luyện tập', icon:Puzzle },
  { id:'write', label:'Viết', icon:PenLine },
  { id:'profile', label:'Hồ sơ', icon:CircleUserRound },
]

export default function App() {
  const [active, setActive] = useState('home')
  const [drawer, setDrawer] = useState(false)
  const [lesson, setLesson] = useState(null)
  const [progress, setProgress] = useState(() => getAllProgress())
  const [errorProfile, setErrorProfile] = useState(() => getErrorProfile())
  const [reviewQueue, setReviewQueue] = useState(() => getReviewQueue())

  useEffect(() => {
    const refreshProgress = () => setProgress(getAllProgress())
    const refreshAttempts = () => { setErrorProfile(getErrorProfile()); setReviewQueue(getReviewQueue()) }
    window.addEventListener('apple-progress-updated', refreshProgress)
    window.addEventListener('bunny-progress-updated', refreshProgress)
    window.addEventListener('apple-attempts-updated', refreshAttempts)
    return () => {
      window.removeEventListener('apple-progress-updated', refreshProgress)
      window.removeEventListener('bunny-progress-updated', refreshProgress)
      window.removeEventListener('apple-attempts-updated', refreshAttempts)
    }
  }, [])

  const errors = useMemo(()=>validateFoundationCurriculum(),[])
  useEffect(()=>{ if(errors.length) console.error('Curriculum validation errors',errors) },[errors])
  const completed = foundationLessons.filter(l=>progress[l.id]?.status==='completed').length
  const firstUnfinished = foundationLessons.find(l=>progress[l.id]?.status!=='completed') || foundationLessons[foundationLessons.length-1]
  const openLessonById = id => { const target = foundationLessonById[id]; if (target) setLesson(target) }

  return <div className="min-h-screen hero-glow text-slate-900">
    <Sidebar active={active} setActive={setActive} completed={completed}/>
    <MobileHeader onMenu={()=>setDrawer(true)}/>
    {drawer&&<Drawer active={active} setActive={setActive} onClose={()=>setDrawer(false)}/>} 
    <main className="mx-auto w-full max-w-[1540px] px-4 pb-28 pt-5 sm:px-6 lg:pl-[280px] lg:pr-8 lg:pt-8">
      {active==='home'&&<HomePage completed={completed} progress={progress} firstUnfinished={firstUnfinished} errorProfile={errorProfile} onContinue={()=>setLesson(firstUnfinished)} onLearn={()=>setActive('learn')} onPractice={()=>setActive('practice')}/>} 
      {active==='learn'&&<FoundationMap onOpenLesson={setLesson}/>} 
      {active==='practice'&&<PracticePage errorProfile={errorProfile} reviewQueue={reviewQueue} onOpenLesson={openLessonById}/>} 
      {active==='write'&&<WritingPage/>} 
      {active==='profile'&&<Profile completed={completed} errorProfile={errorProfile} onReset={()=>{if(confirm('Reset all Foundation progress and error history?')) { resetFoundationProgress(); setProgress({}); setErrorProfile([]); setReviewQueue([]) }}}/>}
    </main>
    <BottomNav active={active} setActive={setActive}/>
    {lesson&&<LessonEngine lesson={lesson} onClose={()=>setLesson(null)} onComplete={()=>{setLesson(null); setActive('learn')}}/>}
  </div>
}

function Logo(){return <div className="flex items-center gap-2.5"><div className="grid h-10 w-10 place-items-center rounded-2xl border border-orange-100 bg-white card-shadow"><Mascot size={38} withBook={false}/></div><div className="leading-none"><div className="text-lg font-black tracking-tight"><span className="text-[#ef4444]">Bunny</span> <span className="text-[#247df4]">English</span></div><div className="mt-1 text-[9px] font-black uppercase tracking-[.18em] text-slate-400">Learn with clarity</div></div></div>}

function Sidebar({active,setActive,completed}){return <aside className="fixed inset-y-0 left-0 z-40 hidden w-[248px] border-r border-slate-200/80 bg-white/90 p-5 backdrop-blur-xl lg:flex lg:flex-col"><Logo/><div className="mt-7 rounded-3xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex items-center gap-3"><Mascot size={54}/><div><p className="text-xs font-bold text-slate-500">Foundation</p><p className="text-xl font-black text-slate-900">{completed}/30</p></div></div><div className="mt-3 h-2 rounded-full bg-white"><div className="h-full rounded-full bg-blue-600" style={{width:`${completed/30*100}%`}}/></div></div><nav className="mt-6 space-y-2">{nav.map(item=>{const I=item.icon; const s=active===item.id; return <button key={item.id} onClick={()=>setActive(item.id)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold ${s?'bg-blue-50 text-blue-700':'text-slate-500 hover:bg-slate-50'}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${s?'bg-blue-600 text-white':'bg-slate-100'}`}><I className="h-4.5 w-4.5"/></span>{item.label}{s&&<ChevronRight className="ml-auto h-4 w-4"/>}</button>})}</nav><div className="mt-auto rounded-3xl bg-[#102958] p-4 text-white"><div className="flex items-center gap-3"><Brain className="h-5 w-5 text-blue-300"/><p className="text-sm font-black">Hiểu trước, nhớ sau</p></div><p className="mt-2 text-xs leading-5 text-blue-100">Bạn sẽ nhận diện → xây câu → sửa lỗi → tự viết. App không cho “đã xem” thay thế “đã nắm”.</p></div></aside>}
function MobileHeader({onMenu}){return <header className="sticky top-0 z-30 flex items-center justify-between border-b border-slate-200/70 bg-[#fffaf4]/90 px-4 py-3 backdrop-blur-xl lg:hidden"><button onClick={onMenu} className="grid h-10 w-10 place-items-center rounded-xl bg-white card-shadow"><Menu className="h-5 w-5"/></button><Logo/><div className="grid h-10 min-w-10 place-items-center rounded-xl bg-white px-2 card-shadow"><span className="text-sm font-black text-orange-500">🔥</span></div></header>}
function Drawer({active,setActive,onClose}){return <div className="fixed inset-0 z-50 lg:hidden"><button onClick={onClose} className="absolute inset-0 bg-slate-900/30"/><div className="absolute left-0 top-0 h-full w-[86%] max-w-sm bg-white p-5 shadow-2xl"><div className="flex justify-between"><Logo/><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><X className="h-5 w-5"/></button></div><nav className="mt-7 space-y-2">{nav.map(item=>{const I=item.icon;return <button key={item.id} onClick={()=>{setActive(item.id);onClose()}} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 font-bold ${active===item.id?'bg-blue-50 text-blue-700':'text-slate-600'}`}><I className="h-5 w-5"/>{item.label}</button>})}</nav></div></div>}
function BottomNav({active,setActive}){return <nav className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-[22px] border border-slate-200/80 bg-white/95 p-1.5 shadow-xl backdrop-blur-xl lg:hidden">{nav.map(item=>{const I=item.icon;const s=active===item.id;return <button key={item.id} onClick={()=>setActive(item.id)} className={`flex flex-col items-center gap-1 rounded-2xl px-1 py-2 text-[10px] font-bold ${s?'bg-blue-50 text-blue-700':'text-slate-400'}`}><I className="h-5 w-5"/>{item.label}</button>})}</nav>}

function HomePage({completed,firstUnfinished,errorProfile,onContinue,onLearn,onPractice}){
  const pct=Math.round(completed/30*100)
  const topWeak=errorProfile.slice(0,3)
  return <div className="space-y-6">
    <section className="overflow-hidden rounded-[32px] border border-orange-100 bg-white card-shadow"><div className="grid gap-5 p-5 md:grid-cols-[1.35fr_.65fr] md:p-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-green-100 bg-green-50 px-3 py-1.5 text-xs font-black text-green-700"><Sparkles className="h-3.5 w-3.5"/> FOUNDATION PATH</div><h1 className="mt-4 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl xl:text-5xl">Học tiếng Anh từ <span className="text-blue-600">câu đầu tiên</span> đến cách tự diễn đạt <span className="text-violet-600">rõ ràng</span>.</h1><p className="mt-4 max-w-3xl text-sm font-medium leading-7 text-slate-500">Bắt đầu thật chắc: hiểu cấu trúc, xây câu, sửa lỗi, rồi tự viết. Khi nền tảng mạnh, cùng hệ thống này có thể đưa bạn lên paragraph, essay và college English.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={onContinue} className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-100">{completed ? 'Tiếp tục học' : 'Bắt đầu Foundation'}</button><button onClick={onLearn} className="rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-black text-slate-700">Xem lộ trình</button></div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Bài tiếp theo</p><p className="mt-1 text-sm font-black text-slate-800">{firstUnfinished.titleEn} <span className="font-semibold text-slate-400">/ {firstUnfinished.titleVi}</span></p></div></div><div className="relative grid min-h-52 place-items-center rounded-[28px] bg-gradient-to-br from-blue-50 via-white to-orange-50 soft-grid"><Mascot size={176} className="floaty"/><div className="absolute bottom-4 right-4 rounded-2xl bg-white px-3 py-2 text-xs font-black text-blue-700 card-shadow">Hiểu trước. Nhớ sau.</div></div></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Foundation" value={`${pct}%`} helper={`${completed}/30 bài đã làm chủ`}/><Metric label="Bài tiếp theo" value={`#${firstUnfinished.order}`} helper={firstUnfinished.titleEn}/><Metric label="Điểm cần ôn" value={String(errorProfile.length)} helper={errorProfile.length ? errorCategoryLabel(errorProfile[0].category) : 'Chưa có lỗi lặp lại'}/></section>
    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-6 card-shadow"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Cách Bunny English dạy</p><h2 className="mt-2 text-2xl font-black">Một khái niệm → nhiều cách chứng minh bạn hiểu.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Khám phá trong ngữ cảnh','Xem English tự nhiên trước khi đọc quy tắc.'],['Hiểu bằng tiếng Việt','Giải thích ngắn, tập trung vào khác biệt quan trọng.'],['Xây và sửa câu','Không chỉ nhận diện; bạn phải thao tác với cấu trúc.'],['Tự viết','Production là điều kiện thật để đi tiếp.']].map(([a,b])=><div key={a} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><p className="text-sm font-black">{a}</p><p className="mt-1 text-xs leading-5 text-slate-500">{b}</p></div>)}</div></div><div className="rounded-[28px] border border-blue-100 bg-blue-50/60 p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Ôn tập cá nhân</p><h2 className="mt-2 text-xl font-black">Điểm bạn hay sai</h2></div><Target className="h-6 w-6 text-blue-600"/></div>{topWeak.length ? <div className="mt-4 space-y-3">{topWeak.map(item=><div key={item.category} className="rounded-2xl bg-white p-3"><div className="flex items-center justify-between"><span className="text-sm font-black text-slate-700">{errorCategoryLabel(item.category)}</span><span className="text-xs font-black text-orange-500">{item.errors} lỗi</span></div></div>)}<button onClick={onPractice} className="mt-1 w-full rounded-2xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Mở phần luyện tập</button></div> : <p className="mt-4 text-sm font-semibold leading-6 text-slate-500">Hãy làm vài bài trước. Khi bạn sai, app sẽ ghi loại lỗi để tạo danh sách ôn tập riêng cho bạn.</p>}</div></section>
  </div>
}

function PracticePage({errorProfile,reviewQueue,onOpenLesson}){
  return <div className="space-y-6"><section className="rounded-[30px] border border-slate-200 bg-white p-6 card-shadow"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-violet-600">Personalized review</p><h1 className="mt-2 text-3xl font-black">Ôn đúng chỗ bạn đang yếu.</h1><p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-slate-500">Mỗi lần trả lời sai, Bunny English lưu loại lỗi và bài liên quan. Khi bạn sửa đúng, lịch sử vẫn giữ để nhận ra lỗi lặp lại thay vì chỉ nhìn điểm tổng.</p></div><div className="hidden h-14 w-14 place-items-center rounded-2xl bg-violet-50 text-violet-600 sm:grid"><Target className="h-6 w-6"/></div></div></section>
    <section className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><h2 className="text-xl font-black">Weakness profile</h2>{errorProfile.length ? <div className="mt-4 space-y-3">{errorProfile.slice(0,8).map(item=><div key={item.category} className="rounded-2xl border border-slate-100 bg-slate-50/60 p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-black text-slate-700">{errorCategoryLabel(item.category)}</span><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-black text-orange-500">{item.errors} lỗi</span></div><p className="mt-1 text-xs font-semibold text-slate-400">Xuất hiện trong {item.lessons} bài</p></div>)}</div> : <EmptyState text="Chưa có lỗi nào được ghi. Làm bài Foundation để hệ thống bắt đầu cá nhân hóa."/>}</div>
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><h2 className="text-xl font-black">Review queue</h2><p className="mt-1 text-xs font-semibold text-slate-400">Các lỗi gần đây để bạn quay lại đúng bài.</p>{reviewQueue.length ? <div className="mt-4 space-y-3">{reviewQueue.map(item=><div key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-black text-orange-700">{errorCategoryLabel(item.errorCategory)}</span>{item.correctedLater && <span className="text-[10px] font-black text-emerald-600">ĐÃ SỬA SAU ĐÓ ✓</span>}</div><p className="mt-3 text-sm font-bold text-slate-700">{item.promptVi}</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-red-50 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-red-400">Bạn đã trả lời</p><p className="mt-1 text-xs font-bold text-red-700">{String(item.answer || '—')}</p></div><div className="rounded-xl bg-emerald-50 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-emerald-500">Mục tiêu</p><p className="mt-1 text-xs font-bold text-emerald-700">{String(item.expected || '—')}</p></div></div><button onClick={()=>onOpenLesson(item.lessonId)} className="mt-3 rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-xs font-black text-blue-700">Mở lại bài {item.lessonTitle}</button></div>)}</div> : <EmptyState text="Review queue đang trống. Các câu sai sẽ tự xuất hiện ở đây."/>}</div></section>
  </div>
}

function WritingPage(){return <div className="space-y-5"><section className="rounded-[30px] border border-slate-200 bg-white p-7 card-shadow"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-600">Writing path</p><h1 className="mt-2 text-3xl font-black">Viết bắt đầu từ Foundation — không đợi đến Essay.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500">Mỗi bài Foundation đã có phần Produce. Khi nền tảng đủ mạnh, tab này sẽ mở rộng cùng engine hiện tại: sentence → paragraph → essay → academic writing. Bản này chưa giả lập AI feedback trước khi service thật được nối vào.</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{['Sentence','Paragraph','Essay','Academic'].map((item,i)=><div key={item} className={`rounded-2xl border p-4 ${i===0?'border-orange-200 bg-orange-50':'border-slate-100 bg-slate-50/60'}`}><p className="text-xs font-black uppercase tracking-wider text-slate-400">Stage {i+1}</p><p className="mt-1 font-black text-slate-800">{item}</p><p className="mt-2 text-xs font-semibold text-slate-400">{i===0?'Đang xây qua Foundation':'Mở sau khi engine đủ chắc'}</p></div>)}</div></section></div>}

function Metric({label,value,helper}){return <div className="rounded-[24px] border border-slate-200 bg-white p-5 card-shadow"><p className="text-xs font-black uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-2 truncate text-xs font-semibold text-slate-500">{helper}</p></div>}
function EmptyState({text}){return <div className="mt-4 rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-5 text-sm font-semibold leading-6 text-slate-400"><AlertCircle className="mb-2 h-5 w-5"/>{text}</div>}
function Profile({completed,errorProfile,onReset}){return <div className="space-y-5"><div className="rounded-[30px] border border-slate-200 bg-white p-7 card-shadow"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-24 w-24 place-items-center rounded-[28px] bg-blue-50"><Mascot size={88}/></div><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Foundation learner</p><h1 className="mt-1 text-3xl font-black">Hồ sơ học tập</h1><p className="mt-2 text-sm text-slate-500">{completed}/30 bài đã làm chủ · {errorProfile.reduce((n,x)=>n+x.errors,0)} lỗi đã được ghi để cá nhân hóa ôn tập.</p></div></div></div><div className="rounded-[28px] border border-slate-200 bg-white p-5 card-shadow"><h2 className="text-lg font-black">Các nhóm lỗi thường gặp</h2>{errorProfile.length ? <div className="mt-4 flex flex-wrap gap-2">{errorProfile.slice(0,10).map(item=><span key={item.category} className="rounded-full bg-slate-50 px-3 py-2 text-xs font-black text-slate-600">{errorCategoryLabel(item.category)} · {item.errors}</span>)}</div> : <p className="mt-3 text-sm font-semibold text-slate-400">Chưa có dữ liệu lỗi.</p>}</div><button onClick={onReset} className="inline-flex items-center gap-2 rounded-2xl border border-red-200 bg-white px-4 py-3 text-sm font-black text-red-600"><RotateCcw className="h-4 w-4"/> Reset Foundation progress</button></div>}
